#############################################################################
# Generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#  Jan 18, 2020 07:25:28 PM CET  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu {{}} -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 935x725+356+176
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3204 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Bioinformatics"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    ttk::style configure TNotebook -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -foreground $vTcl(actual_gui_fg)
    ttk::style configure TNotebook.Tab -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style map TNotebook.Tab -background [list disabled $vTcl(actual_gui_bg) selected $vTcl(pr,guicomplement_color)]
    ttk::notebook $top.tNo48 \
        -takefocus {} 
    vTcl:DefineAlias "$top.tNo48" "TNotebook1" vTcl:WidgetProc "Toplevel1" 1
    frame $top.tNo48.t0 \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo48.t0" "TNotebook1_t0" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo48 add $top.tNo48.t0 \
        -padding 0 -sticky nsew -state normal -text {MSA Calculator} \
        -image {} -compound left -underline -1 
    set site_4_0  $top.tNo48.t0
    label $site_4_0.lab44 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text MSA 
    vTcl:DefineAlias "$site_4_0.lab44" "Label1" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_4_0.tCo50 \
        -font TkTextFont -invalidcommand set_methods -textvariable combobox1 \
        -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$site_4_0.tCo50" "SelectProgram" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but51 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command calculate_default \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Calculate MSA} 
    vTcl:DefineAlias "$site_4_0.but51" "CalculateDefault" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab56 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Sequences 
    vTcl:DefineAlias "$site_4_0.lab56" "Label2" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but57 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command load_file \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Load sequences} 
    vTcl:DefineAlias "$site_4_0.but57" "LoadFileButton" vTcl:WidgetProc "Toplevel1" 1
    vTcl::widgets::ttk::scrolledtext::CreateCmd $site_4_0.scr47 \
        -background $vTcl(actual_gui_bg) -height 75 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 125 
    vTcl:DefineAlias "$site_4_0.scr47" "OutputText" vTcl:WidgetProc "Toplevel1" 1

    $site_4_0.scr47.01 configure -background white \
        -blockcursor 1 \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -state disabled \
        -width 10 \
        -wrap none
    vTcl::widgets::ttk::scrolledtext::CreateCmd $site_4_0.scr48 \
        -background $vTcl(actual_gui_bg) -height 75 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 125 
    vTcl:DefineAlias "$site_4_0.scr48" "InputText" vTcl:WidgetProc "Toplevel1" 1

    $site_4_0.scr48.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -wrap none
    vTcl::widgets::ttk::scrolledtext::CreateCmd $site_4_0.scr43 \
        -background $vTcl(actual_gui_bg) -height 75 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 125 
    vTcl:DefineAlias "$site_4_0.scr43" "Consensus" vTcl:WidgetProc "Toplevel1" 1

    $site_4_0.scr43.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -wrap none
    vTcl::widgets::ttk::scrolledtext::CreateCmd $site_4_0.scr44 \
        -background $vTcl(actual_gui_bg) -height 75 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 125 
    vTcl:DefineAlias "$site_4_0.scr44" "PSSM" vTcl:WidgetProc "Toplevel1" 1

    $site_4_0.scr44.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -wrap none
    label $site_4_0.lab45 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Consensus word} 
    vTcl:DefineAlias "$site_4_0.lab45" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab46 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Position Specific Scoring Matrix} 
    vTcl:DefineAlias "$site_4_0.lab46" "Label4" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.lab44 \
        -in $site_4_0 -x 530 -y 40 -width 54 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tCo50 \
        -in $site_4_0 -x 60 -y 600 -anchor nw -bordermode ignore 
    place $site_4_0.but51 \
        -in $site_4_0 -x 300 -y 600 -anchor nw -bordermode ignore 
    place $site_4_0.lab56 \
        -in $site_4_0 -x 40 -y 40 -anchor nw -bordermode ignore 
    place $site_4_0.but57 \
        -in $site_4_0 -x 40 -y 370 -anchor nw -bordermode ignore 
    place $site_4_0.scr47 \
        -in $site_4_0 -x 540 -y 80 -width 381 -relwidth 0 -height 271 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.scr48 \
        -in $site_4_0 -x 40 -y 80 -width 401 -relwidth 0 -height 281 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.scr43 \
        -in $site_4_0 -x 540 -y 400 -width 381 -relwidth 0 -height 51 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.scr44 \
        -in $site_4_0 -x 540 -y 540 -width 381 -relwidth 0 -height 141 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab45 \
        -in $site_4_0 -x 540 -y 370 -anchor nw -bordermode ignore 
    place $site_4_0.lab46 \
        -in $site_4_0 -x 540 -y 510 -anchor nw -bordermode ignore 
    frame $top.tNo48.t2 \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo48.t2" "TNotebook1_t1" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo48 add $top.tNo48.t2 \
        -padding 0 -sticky nsew -state normal -text {MSA Converter} -image {} \
        -compound none -underline -1 
    set site_4_1  $top.tNo48.t2
    button $site_4_1.but43 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command convert_file \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Convert 
    vTcl:DefineAlias "$site_4_1.but43" "ConvertButton" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_1.but45 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command load_file_to_convert \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Load file} 
    vTcl:DefineAlias "$site_4_1.but45" "Button1" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_1.lab46 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -textvariable FileToConvertName 
    vTcl:DefineAlias "$site_4_1.lab46" "FileToConvertNameLabel" vTcl:WidgetProc "Toplevel1" 1
    vTcl::widgets::ttk::scrolledtext::CreateCmd $site_4_1.scr47 \
        -background $vTcl(actual_gui_bg) -height 75 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 125 
    vTcl:DefineAlias "$site_4_1.scr47" "FileToConvertText" vTcl:WidgetProc "Toplevel1" 1

    $site_4_1.scr47.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -state disabled \
        -width 10 \
        -wrap none
    vTcl::widgets::ttk::scrolledtext::CreateCmd $site_4_1.scr48 \
        -background $vTcl(actual_gui_bg) -height 75 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 125 
    vTcl:DefineAlias "$site_4_1.scr48" "ConvertedFileText" vTcl:WidgetProc "Toplevel1" 1

    $site_4_1.scr48.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -state disabled \
        -width 10 \
        -wrap none
    ttk::label $site_4_1.tLa49 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -textvariable ConvertedFileName 
    vTcl:DefineAlias "$site_4_1.tLa49" "ConvertedFileNameLabel" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_1.but43 \
        -in $site_4_1 -x 400 -y 240 -width 147 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.but45 \
        -in $site_4_1 -x 130 -y 570 -width 127 -relwidth 0 -height 54 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.lab46 \
        -in $site_4_1 -x 30 -y 510 -width 334 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.scr47 \
        -in $site_4_1 -x 30 -y 30 -width 341 -relwidth 0 -height 461 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.scr48 \
        -in $site_4_1 -x 570 -y 30 -width 351 -relwidth 0 -height 461 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.tLa49 \
        -in $site_4_1 -x 570 -y 510 -width 344 -relwidth 0 -height 39 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.tNo48.t1 \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo48.t1" "TNotebook1_t2" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo48 add $top.tNo48.t1 \
        -padding 0 -sticky nsew -state normal -text {Phylogenetic Trees} \
        -image {} -compound left -underline -1 
    set site_4_2  $top.tNo48.t1
    canvas $site_4_2.can47 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -closeenough 1.0 \
        -height 483 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -insertbackground black -relief ridge \
        -selectbackground #c4c4c4 -selectforeground black -width 643 
    vTcl:DefineAlias "$site_4_2.can47" "TreeCanvas" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_2.but48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command load_tree \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Load Tree} 
    vTcl:DefineAlias "$site_4_2.but48" "LoadTree" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_2.ent49 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$site_4_2.ent49" "AncestorEntry" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_2.but50 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command common_ancestor \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Find Common Ancestor} 
    vTcl:DefineAlias "$site_4_2.but50" "Button3" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_2.ent51 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$site_4_2.ent51" "PathLeaf" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_2.but52 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command draw_path \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Draw path from root} 
    vTcl:DefineAlias "$site_4_2.but52" "bsadasdasdasd" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_2.lab53 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -textvariable NumberOfLeafs 
    vTcl:DefineAlias "$site_4_2.lab53" "NumberOfLeafsLabel" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_2.lab54 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$site_4_2.lab54" "DistanceFromRoot" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_2.lab55 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -textvariable TreeLength -wraplength 80 
    vTcl:DefineAlias "$site_4_2.lab55" "TreeLengthLabel" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_2.ent43 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$site_4_2.ent43" "DistanceEntry1" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_2.ent44 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$site_4_2.ent44" "DistanceEntry2" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_2.but45 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command calculate_distance \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Calculate Distance} 
    vTcl:DefineAlias "$site_4_2.but45" "Button4" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_2.lab46 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -textvariable distance 
    vTcl:DefineAlias "$site_4_2.lab46" "Label5" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_2.can47 \
        -in $site_4_2 -x 140 -y 0 -width 643 -relwidth 0 -height 483 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.but48 \
        -in $site_4_2 -x 20 -y 150 -width 107 -relwidth 0 -height 54 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.ent49 \
        -in $site_4_2 -x 130 -y 520 -anchor nw -bordermode ignore 
    place $site_4_2.but50 \
        -in $site_4_2 -x 320 -y 520 -anchor nw -bordermode ignore 
    place $site_4_2.ent51 \
        -in $site_4_2 -x 130 -y 550 -anchor nw -bordermode ignore 
    place $site_4_2.but52 \
        -in $site_4_2 -x 320 -y 550 -anchor nw -bordermode ignore 
    place $site_4_2.lab53 \
        -in $site_4_2 -x 790 -y 0 -width 134 -relwidth 0 -height 41 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.lab54 \
        -in $site_4_2 -x 470 -y 550 -anchor nw -bordermode ignore 
    place $site_4_2.lab55 \
        -in $site_4_2 -x 790 -y 50 -width 134 -relwidth 0 -height 91 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.ent43 \
        -in $site_4_2 -x 130 -y 580 -anchor nw -bordermode ignore 
    place $site_4_2.ent44 \
        -in $site_4_2 -x 310 -y 580 -anchor nw -bordermode ignore 
    place $site_4_2.but45 \
        -in $site_4_2 -x 490 -y 580 -anchor nw -bordermode ignore 
    place $site_4_2.lab46 \
        -in $site_4_2 -x 620 -y 580 -width 114 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.tNo48.t4 \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo48.t4" "TNotebook1_t3" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo48 add $top.tNo48.t4 \
        -padding 0 -sticky nsew -state normal -text {Tree constructor} \
        -image {} -compound none -underline -1 
    set site_4_3  $top.tNo48.t4
    button $site_4_3.but44 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command load_msa_for_tree \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Load MSA} 
    vTcl:DefineAlias "$site_4_3.but44" "Button5" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_3.lab45 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -textvariable loaded_msa_tree 
    vTcl:DefineAlias "$site_4_3.lab45" "Label6" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_3.but46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command create_tree_distance \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Create tree (distance)} 
    vTcl:DefineAlias "$site_4_3.but46" "Button6" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_4_3.tCo47 \
        -font TkTextFont -textvariable combobox2 -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$site_4_3.tCo47" "AlgorithmCombo" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_3.lab48 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -text Algorithm 
    vTcl:DefineAlias "$site_4_3.lab48" "Label7" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_3.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command create_tree_parsimony \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Create tree (parsimony)} 
    vTcl:DefineAlias "$site_4_3.but49" "Button7" vTcl:WidgetProc "Toplevel1" 1
    canvas $site_4_3.can50 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -closeenough 1.0 \
        -height 483 -insertbackground black -relief ridge \
        -selectbackground #c4c4c4 -selectforeground black -width 643 
    vTcl:DefineAlias "$site_4_3.can50" "CreatedTreeCanvas" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_3.but44 \
        -in $site_4_3 -x 30 -y 40 -anchor nw -bordermode ignore 
    place $site_4_3.lab45 \
        -in $site_4_3 -x 10 -y 80 -width 256 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_3.but46 \
        -in $site_4_3 -x 90 -y 610 -anchor nw -bordermode ignore 
    place $site_4_3.tCo47 \
        -in $site_4_3 -x 110 -y 560 -anchor nw -bordermode ignore 
    place $site_4_3.lab48 \
        -in $site_4_3 -x 20 -y 560 -anchor nw -bordermode ignore 
    place $site_4_3.but49 \
        -in $site_4_3 -x 610 -y 610 -anchor nw -bordermode ignore 
    place $site_4_3.can50 \
        -in $site_4_3 -x 270 -y 20 -width 643 -relwidth 0 -height 483 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.tNo48.t3 \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo48.t3" "TNotebook1_t4" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo48 add $top.tNo48.t3 \
        -padding 0 -sticky nsew -state normal -text {Consensus Trees} \
        -image {} -compound none -underline -1 
    set site_4_4  $top.tNo48.t3
    button $site_4_4.but43 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command load_consensus_trees \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Load trees} 
    vTcl:DefineAlias "$site_4_4.but43" "Button2" vTcl:WidgetProc "Toplevel1" 1
    canvas $site_4_4.can51 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -closeenough 1.0 \
        -height 483 -insertbackground black -relief ridge \
        -selectbackground #c4c4c4 -selectforeground black -width 643 
    vTcl:DefineAlias "$site_4_4.can51" "ConsensusTreeCanvas" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_4.lab52 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -text {Consensus Tree} 
    vTcl:DefineAlias "$site_4_4.lab52" "Label8" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_4.lab53 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -text Mode 
    vTcl:DefineAlias "$site_4_4.lab53" "Label9" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_4.lab54 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -text {Cutoff(majority mode only)} 
    vTcl:DefineAlias "$site_4_4.lab54" "Label10" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_4.ent55 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black \
        -textvariable cutoff_value 
    vTcl:DefineAlias "$site_4_4.ent55" "Cutoff" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_4_4.tCo56 \
        -exportselection 0 -font TkTextFont -textvariable combobox3 \
        -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$site_4_4.tCo56" "ConsensusMode" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_4.but43 \
        -in $site_4_4 -x 270 -y 520 -anchor nw -bordermode ignore 
    place $site_4_4.can51 \
        -in $site_4_4 -x 260 -y 10 -width 643 -relwidth 0 -height 483 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_4.lab52 \
        -in $site_4_4 -x 500 -y 500 -width 204 -relwidth 0 -height 51 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_4.lab53 \
        -in $site_4_4 -x 30 -y 90 -anchor nw -bordermode ignore 
    place $site_4_4.lab54 \
        -in $site_4_4 -x 30 -y 200 -width 154 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_4.ent55 \
        -in $site_4_4 -x 30 -y 230 -anchor nw -bordermode ignore 
    place $site_4_4.tCo56 \
        -in $site_4_4 -x 30 -y 130 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tNo48 \
        -in $top -x 0 -y 0 -width 0 -relwidth 1 -height 0 -relheight 1 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

